@Book{1,
 year      = {4},
 author    = {2},
 publisher = {5},
 title     = {3},
}

@Book{1,
 year      = {4},
 author    = {2},
 publisher = {5},
 title     = {3},
}

@Book{a,
 year      = {d},
 author    = {},
 publisher = {f},
 title     = {s},
}

@Book{1,
 year      = {4},
 author    = {2},
 publisher = {5},
 title     = {3},
}

@Book{q,
 year      = {r},
 author    = {w},
 publisher = {t},
 title     = {e},
}


